#!/bin/bash
#SBATCH --verbose
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --job-name=Michael
#SBATCH --mem=100G
#SBATCH --partition=reservation
#SBATCH --reservation=eece5640
$SRUN mpirun -mca btl_base_warn_component_unused 0 ~/HPC/A4/Q1/PartA/Q1A
